### ISSUE TITLE
New release on crates.io?

### ISSUE THREAD

**Issue by Mallets** [smol-rs/async-rustls#10]
Hello async-rustls team!

I have seen that https://github.com/smol-rs/async-rustls/pull/9 has been merged and now `async-rustls` points to the latest `rustls` version.
We are planning to publish on `crates.io` a crate that depends on `async-rustls` and it would be great to be able point to the latest release.

Is there any plan to publish it on `crates.io`?

Thanks for your work!

**Comment by DariusIMP** [comment]
Thank you!
