### ISSUE TITLE
Self Signed Certificate usage?

### ISSUE THREAD

**Issue by eminfedar** [smol-rs/async-rustls#12]
I want to use `ClientConfig`s `dangerous()` function with the feature `dangerous_configuration` on Cargo.toml

This is because I want to connect a server which uses self signed certificates.

But `TlsConnector::from` only accepts `Arc<ClientConfig>` so I can't.

How can I do this? Thanks!

**Comment by notgull** [comment]
This should work:

```rust
let mut client_config: ClientConfig = /* ... */;
// Use the dangerous() method with a mut ref.
client_config.dangerous().set_certificate_verifier(/* ... */);
// Now you can use the original client config.
let cc = Arc::new(client_config);
```

**Comment by notgull** [comment]
Closing this issue since it seems to have worked out. Let me know if you have any other questions.
