### ISSUE TITLE
New release on crates.io?

### ISSUE THREAD

**Issue by Mallets** [smol-rs/async-rustls#18]
Hello async-rustls team!

https://github.com/smol-rs/async-rustls/pull/14 has been merged and now `async-rustls` supports IP-based certificates.
We are planning for next week to publish on crates.io a crate that depends on `async-rustls` and it would be great to be able point to the latest release.

Is there any plan to publish it on crates.io?

Thanks for your work!

**Comment by notgull** [comment]
Huh, I could've sworn I created a release for this crate back when I was releasing all of the `smol-rs` crates.

Oh well, #19

**Comment by notgull** [comment]
Version 0.4.0 has been released!

**Comment by Mallets** [comment]
Thank you very much!!!
