### ISSUE TITLE
Simplify construction/conversion to server::TlsStream

### ISSUE THREAD

**Issue by FlorianUekermann** [smol-rs/async-rustls#20]
A number of very similar crates have gained some popularity. The most popular one that fulfills almost exactly the same role as async-rustls being futures-rustls. For me as a crate author (rustls-acme), this poses a bit of a challenge, because I have to pick one async tls implementation and implicitly exclude those who happen to use another one.
Given that the `server::TlsStream` implementations of rustls based async tls crates are pretty much identical to the letter, it would be very easy to convert between them given some way of constructing a `server::TlsStream` from a `rustls::server::ServerConnection` and an IO stream.
This would allow me to produce async-rustls streams for those who want to use my crate, without forcing them to switch to futures-rustls ( FlorianUekermann/rustls-acme#46 ).

There are a number of ways to go about this, which are all valid imo, so I wanted to open an issue before sending a PR.
What would you prefer?

1. Assuming the connection is in stream state: `fn from<IO>(rustls::server::ServerConnection, io: IO) -> server::TlsStream<IO>`
2. No shutdown state assumptions: `fn from<IO>(rustls::server::ServerConnection, io: IO, read_shutdown, write_shutdown) -> server::TlsStream<IO>`
3. Perform some additional checks (?) `fn try_from<IO>(rustls::server::ServerConnection, io: IO, read_shutdown, write_shutdown) -> Result<server::TlsStream<IO>, ???>`
4. I'm sure there are other ways that make sense...

Personally, I think 1. is sufficient, but 2. seems reasonable as well.

Because users already have `&mut` access to the underlying transport and rustls state anyway (via `server::TlsStream::get_mut`), I'm not worried about invalid `server::TlsStream` instances being constructed. Everything you can accomplish by abusing `impl From` is already possible via `get_mut`, if you want to shoot yourself in the foot.

**Comment by taiki-e** [comment]
We have deprecated this crate in favor of futures-rustls (See #33 for details). Therefore, we recommend considering switching to it.
