### ISSUE TITLE
Deprecate in favor of futures-rustls maintained by rustls team

### ISSUE THREAD

**Issue by taiki-e** [smol-rs/async-rustls#33]
https://github.com/rustls/futures-rustls (which provides the equivalent of this crate, but is usually updated somewhat quickly to the latest rustls) is now maintained by rustls team, so I would like to deprecate this crate in favor of the official one.

@smol-rs/admins: Any opposition? If not, I'll do this 2 weeks later.

**Comment by notgull** [comment]
As long as `futures-rustls` is maintained I'm fine with this.

**Comment by fogti** [comment]
same

**Comment by zeenix** [comment]
👍
