### ISSUE TITLE
Would a rustls 0.20 PR be welcome?

### ISSUE THREAD

**Issue by jbr** [smol-rs/async-rustls#8]
I thought I'd check before opening a PR in case there's already work on this. Thanks!

Intended approach: Holding a rustls::Connection in both client and server instead of ClientSession and ServerSession, dropping the associated Session type from the IoSession trait, and making TlsAcceptor::accept and TlsAcceptor::accept_with return a Result in order to propagate errors from rustls. Possibly also renaming anything *Session with *Connection for concordance with rustls' new naming conventions.

**Comment by taiki-e** [comment]
Thanks. The approach you're thinking looks good to me. I would accept a PR that does this.

**Comment by parazyd** [comment]
Yes please.

**Comment by trinity-1686a** [comment]
Hi, is there any plan to do a release with support for rustls 0.20 yet?
